cmake_minimum_required(VERSION 4.2)
project(DSA_Practice)

set(CMAKE_CXX_STANDARD 20)

add_executable(DSA_Practice main.cpp
        Graphs/TopologicalSort.cpp
        Graphs/TopologicalSort.h
        Arrays/ContainsDuplicate.cpp
        Arrays/ContainsDuplicate.h
        Arrays/ValidAnagram.cpp
        Arrays/ValidAnagram.h
        Arrays/TwoSum.cpp
        Arrays/TwoSum.h
        Arrays/GroupAnagrams.cpp
        Arrays/GroupAnagrams.h
        Arrays/TopKFrequentElements.cpp
        Arrays/TopKFrequentElements.h
        Intervals/MergeIntervals.cpp
        Intervals/MergeIntervals.h
        Arrays/EncodeAndDecodeStrings.cpp
        Arrays/EncodeAndDecodeStrings.h
        Arrays/ProductExceptSelf.cpp
        Arrays/ProductExceptSelf.h
        Arrays/LongestConsecutiveSequence.cpp
        Arrays/LongestConsecutiveSequence.h
        BinarySearch/BinarySearch.cpp
        BinarySearch/BinarySearch.h
        Arrays/ValidSudoku.cpp
        Arrays/ValidSudoku.h
        Stack/ValidParentheses.cpp
        Stack/ValidParentheses.h
        Heap/LastStoneWeight.cpp
        Heap/LastStoneWeight.h
        TwoPointers/ValidPalindrome.cpp
        TwoPointers/ValidPalindrome.h
        TwoPointers/TwoSumTwo.cpp
        TwoPointers/TwoSumTwo.h
        TwoPointers/ThreeSum.cpp
        TwoPointers/ThreeSum.h
        TwoPointers/ContainerWithMostWater.cpp
        TwoPointers/ContainerWithMostWater.h
        TwoPointers/TrappingRainWater.cpp
        TwoPointers/TrappingRainWater.h
        SlindingWindow/BestTimetoBuyandSellStock.cpp
        SlindingWindow/BestTimetoBuyandSellStock.h
        SlindingWindow/LongestSubstringWithoutRepeatingCharacters.cpp
        SlindingWindow/LongestSubstringWithoutRepeatingCharacters.h
        SlindingWindow/LongestRepeatingCharacterReplacement.cpp
        SlindingWindow/LongestRepeatingCharacterReplacement.h
        Heap/KthLargestElementinaStream.cpp
        Heap/KthLargestElementinaStream.h
        SlindingWindow/PermutationinString.cpp
        SlindingWindow/PermutationinString.h
        SlindingWindow/MinimumWindowSubstring.cpp
        SlindingWindow/MinimumWindowSubstring.h
        Stack/MinStack.cpp
        Stack/MinStack.h
        Stack/ReversePolishNotation.cpp
        Stack/ReversePolishNotation.h
)
